### ISSUE TITLE
Wish list heart seletion

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#14]
when clicking heart ON TOP OF LIST in scanned product list, it correctly selects everything. it should also ask which zone or zones.

PLEASE THIS IS IMPORTANT: when clicking on top... it DESELECTS ALL .

this is ok... BUT SHOULD ASK!!!!
thankyou

**Comment by hriziya** [comment]
Done..

**Comment by rafdelre** [comment]
Sergio there is a problem because I see a Variant not present when selecting all from list and applying zones.

**Comment by sergiostrampelli** [comment]
The App makes an invalid request:

``` json
{"id":"33","jsonrpc":"2.0","method":"Item.list","params":{"variantId":"","sessionId":"18f682b9-dece-11e4-b4aa-0cc47a127a14"}}
```

The **variantId** parameter is optional, but cannot be empty!!!

``` json
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"Variant id not specified"},
"id":"33"}
```

This is the example of a correct request:

``` json
{"id":"33","jsonrpc":"2.0","method":"Item.list","params":{"sessionId":"18f682b9-dece-11e4-b4aa-0cc47a127a14"}}
```

### PS

I see that you don't use a random Id and this will lead to a problem in debugging when there will be concurrent requests.

**Comment by sergiostrampelli** [comment]
When in the box there is one or more products that don't have variantId (the app shows "Non Disponibile" this is correct)
BUT, when you click on TOP heart (meaning select all to wish list, select one or more zones and X),  the App tries to add only one item without variantId and 

```
{"id":"33","jsonrpc":"2.0","method":"Item.create","params":{"sessionId":"c2b9c0a2-dee3-11e4-b4aa-0cc47a127a14","items":[{"variantId":"","zoneId":"ace73d9e-c98c-11e4-b4aa-0cc47a127a14"}]}}
```

Then the app locks down (no more rpc call) and must be terminated.
When restarted, the app remains with the "Y" logo for about 10 seconds (should ask for an auth_token).

After this pause, the Qr.find function works, but use the same Auth_token used before the termination.

The Session.read fails because there is no valid auth token.

Only after a second termination, the App works again.

This beahavior is not constant: other times the app continue to work, but when scanning the same QR show all products selected (**the App doesn't call Item.list**).

**Comment by rafdelre** [comment]
Also, the heart inside the Product Detail should work as the one in the list for single row
that is should be selected if in wish list and deselected if not and behave as the one in the list, NOT like the one on top of list.

**Comment by hriziya** [comment]
FIxed all.

**Comment by rafdelre** [comment]
Yes it is fixed. Please disable the function SELECT ALL (heart on top of product list)
It creates only confusion.
Leave everything else the way it is.
It is perfect.

In product detail it is working correctly
thankyou

**Comment by rafdelre** [comment]
Ok
